import {
  IntervalsIcuActivity,
  IntervalsIcuStream,
} from '../../types/intervals-icu';

/**
 * Fixtures recorded from a live probe of a real Intervals.icu account
 * (athlete i225849, 2026-08-07). Field values and shapes are verbatim; the
 * long streams are truncated to a handful of samples.
 */

/** Outdoor road ride recorded on a Garmin Edge 1040 with a Quarq power meter. */
export const outdoorRideActivity: IntervalsIcuActivity = {
  id: 'i167939639',
  name: 'Marin County Road Cycling',
  type: 'Ride',
  sub_type: null,
  start_date: '2026-06-28T19:18:28Z',
  start_date_local: '2026-06-28T12:18:28',
  timezone: 'America/Los_Angeles',
  moving_time: 5781,
  elapsed_time: 6978,
  distance: 34988.06,
  total_elevation_gain: 638.0,
  average_speed: 6.045,
  max_speed: 15.2,
  average_cadence: 75.39,
  // Null even though this ride has a power meter: the populated field is icu_average_watts.
  average_watts: null,
  icu_average_watts: 202,
  icu_weighted_avg_watts: 251,
  max_watts: 741,
  average_heartrate: 145,
  max_heartrate: 172,
  icu_joules: 1167762,
  calories: 1334,
  icu_training_load: 93,
  power_load: 93,
  hr_load: 58,
  pace_load: null,
  trimp: 60.18,
  icu_rpe: null,
  perceived_exertion: null,
  source: 'GARMIN_CONNECT',
  device_name: 'Garmin Edge 1040',
  file_type: 'fit',
  external_id: '23411987686',
  strava_id: null,
  trainer: null,
  gap: null,
  description: null,
  stream_types: [
    'time',
    'watts',
    'cadence',
    'heartrate',
    'distance',
    'altitude',
    'latlng',
    'velocity_smooth',
    'temp',
    'left_right_balance',
    'torque',
  ],
};

/** Zwift virtual run: no power stream, running-specific load. */
export const virtualRunActivity: IntervalsIcuActivity = {
  id: 'i173247669',
  name: 'Zwift - Royal Pump Room 8 in Yorkshire',
  type: 'VirtualRun',
  start_date: '2026-08-07T01:33:08Z',
  start_date_local: '2026-08-06T18:33:08',
  moving_time: 1806,
  elapsed_time: 1806,
  distance: 5363.75,
  total_elevation_gain: 41,
  average_speed: 2.965,
  gap: 3.0489,
  average_cadence: 78.09,
  average_watts: null,
  icu_average_watts: null,
  average_heartrate: 130,
  max_heartrate: 151,
  calories: 409,
  icu_training_load: 32,
  pace_load: 32,
  hr_load: 14,
  trimp: 28.98,
  source: 'ZWIFT',
  device_name: 'ZWIFT 1',
  trainer: true,
  file_type: 'fit',
  external_id: '2199138722820177968',
  stream_types: [
    'time',
    'cadence',
    'heartrate',
    'distance',
    'altitude',
    'latlng',
    'velocity_smooth',
  ],
};

/**
 * Stream response shape, truncated to 4 samples.
 *
 * Note `latlng`: latitude lives in `data`, longitude in `data2`. Every other
 * stream leaves `data2` null.
 */
export const outdoorRideStreams: IntervalsIcuStream[] = [
  {
    type: 'time',
    name: null,
    data: [0, 1, 2, 3],
    data2: null,
    valueType: 'java.lang.Integer',
    valueTypeIsArray: false,
    allNull: false,
    custom: false,
  },
  {
    type: 'watts',
    name: null,
    data: [0, 145, 210, 198],
    data2: null,
    valueType: 'java.lang.Integer',
    valueTypeIsArray: false,
    allNull: false,
    custom: false,
  },
  {
    type: 'heartrate',
    name: null,
    data: [92, 96, 103, 110],
    data2: null,
    valueType: 'java.lang.Integer',
    valueTypeIsArray: false,
    allNull: false,
    custom: false,
  },
  {
    type: 'cadence',
    name: null,
    data: [0, 62, 74, 78],
    data2: null,
    valueType: 'java.lang.Integer',
    valueTypeIsArray: false,
    allNull: false,
    custom: false,
  },
  {
    type: 'distance',
    name: null,
    data: [0, 3.1, 8.4, 14.9],
    data2: null,
    valueType: 'java.lang.Float',
    valueTypeIsArray: false,
    allNull: false,
    custom: false,
  },
  {
    type: 'altitude',
    name: null,
    data: [12.2, 12.4, 12.8, 13.1],
    data2: null,
    valueType: 'java.lang.Float',
    valueTypeIsArray: false,
    allNull: false,
    custom: false,
  },
  {
    type: 'latlng',
    name: null,
    data: [37.906, 37.9061, 37.9063, 37.9065],
    data2: [-122.5449, -122.5451, -122.5453, -122.5456],
    valueType: 'java.lang.Float',
    valueTypeIsArray: false,
    allNull: false,
    custom: false,
  },
  {
    type: 'temp',
    name: null,
    data: [18, 18, 19, 19],
    data2: null,
    valueType: 'java.lang.Integer',
    valueTypeIsArray: false,
    allNull: false,
    custom: false,
  },
  // Streams OpenAthlete has nowhere to store; they must be dropped, not smuggled in.
  {
    type: 'velocity_smooth',
    name: null,
    data: [0, 3.1, 5.3, 6.5],
    data2: null,
    valueType: 'java.lang.Float',
    valueTypeIsArray: false,
    allNull: false,
    custom: false,
  },
  {
    type: 'torque',
    name: null,
    data: [0, 21.4, 27.1, 25.9],
    data2: null,
    valueType: 'java.lang.Float',
    valueTypeIsArray: false,
    allNull: false,
    custom: false,
  },
  {
    type: 'left_right_balance',
    name: null,
    data: [50, 49, 51, 50],
    data2: null,
    valueType: 'java.lang.Integer',
    valueTypeIsArray: false,
    allNull: false,
    custom: false,
  },
];

/** The 401 body Intervals.icu returns for both a bad key and a rate-limit block. */
export const authFailedBody = { status: 401, error: 'Auth failed' };
